### ISSUE TITLE
Error building grpc source code

### ISSUE THREAD

**Issue by sjpritchard** [GoogleCloudPlatform/cpp-samples#113] opened 2021-02-02 11:12 UTC
I'm getting the following error when building grpc C++ source code from https://github.com/googleapis/googleapis using protoc 3.14.0 and grpc 1.35.0 on Ubuntu 20.10 (WSL). Same issue as #98. 

`protoc --proto_path=.:/usr/local/include --cpp_out=./gens --grpc_out=./gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin google/maps/routes/v1/route_service.proto
[libprotobuf FATAL /home/xxxx/xxxxx/grpc/third_party/protobuf/src/google/protobuf/io/printer.cc:142]  Unclosed variable name.
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():   Unclosed variable name.
--grpc_out: protoc-gen-grpc: Plugin killed by signal 6.
make: *** [Makefile:45: google/maps/routes/v1/route_service.pb.cc] Error 1`

**Comment by coryan** [comment] 2021-02-02 14:18
That you for filing a report.  Looking at the error message this seems like a gRPC plugin crashing, possibly related to this:

https://github.com/grpc/grpc/issues/8741

**Comment by coryan** [comment] 2021-02-08 13:45
Okay, my first attempt at reproducing this failed. I created a Dockerfile to compile protobuf, gRPC, and googleapis on Ubuntu:20.04 and it works without problems:

[repro-cpp-samples-113.Dockerfile](https://github.com/GoogleCloudPlatform/cpp-samples/files/5944020/repro-cpp-samples-113.Dockerfile.txt)

**Comment by coryan** [comment] 2021-02-08 13:52
Second attempt with Ubuntu:20.10 does not repro either.

@sjpritchard Maybe you can look at the attached Dockerfiles and tell me what I am doing wrong / different?

[repro-cpp-samples-113.Dockerfile](https://github.com/GoogleCloudPlatform/cpp-samples/files/5944058/repro-cpp-samples-113.Dockerfile.txt)

**Comment by MJBGO** [comment] 2021-02-12 13:32
Hello ! Same error for me :

![image](https://user-images.githubusercontent.com/8344487/107771823-a5f92a00-6d3b-11eb-8a99-1ce51941cf19.png)

I'm using :

- last Ubuntu version but not with dockerfile, directly on the machine.
- last protobuf version (v3.14), compiled with ./configure && make && make check && sudo make install && sudo ldconfig
- last grpc version (v1.35), compiled with mkdir -p cmake/build && cd cmake/build && cmake ../.. && make && sudo make install && sudo ldconfig
- last googleapis version, compiled with make all

**Comment by coryan** [comment] 2021-02-12 14:10
@MJBGO Thanks, we must be doing something different because it obviously works for me.  Can you help me troubleshoot the differences by answering some questions?  I am trying to run the build steps as you describe them at the same time.

- protobuf does not ship with a `configure` script, I assume you had to run `./autogen.sh` ?
- gRPC needs Abseil and RE2 and c-ares, how did you compile/install those? Did you use the git modules for gRPC?
- Do you have any system protobuf packages installed?  Like `libprotobuf-dev` or maybe 

What are the results from:

```shell
ldd /usr/local/bin/protoc
```

and

```shell
ldd /usr/local/bin/grpc_cpp_plugin
```

**Comment by coryan** [comment] 2021-02-19 16:08
Ping, I am still unable to reproduce the problem.  Since the Dockerfile I attached above includes reproducible steps that get things working I am inclined to close this unless I hear of a way to reproduce these issues.

**Comment by mpietras** [comment] 2021-02-19 18:53
I have the same compile issue mentioned in this issue...  build grpc v1.35.0 which also built protoc v3.14.0 then cloned googleapis and built... "printer.cc:142 Unclosed variable name" found this looking for help.

**Comment by coryan** [comment] 2021-02-19 19:04
@mpietras fair enough.  I do believe that the problem is real, but I just cannot reproduce it.  I image this is frustrating for folks wanting an answer, it is frustrating to be unable to give you one.

If you could share more details of how you built gRPC and protobuf that would help.  In general, a set of detailed steps to reproduce the problem would be appreciated.

**Comment by mpietras** [comment] 2021-02-19 19:04
\~/googleapis# ldd /usr/local/bin/protoc
linux-vdso.so.1 (0x00007fff6d9e1000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f94b6451000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f94b6270000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f94b6255000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f94b6063000)
/lib64/ld-linux-x86-64.so.2 (0x00007f94b6d59000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f94b5f14000)

\~/googleapis# ldd /usr/local/bin/grpc_cpp_plugin
linux-vdso.so.1 (0x00007ffff1f63000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0a424ac000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0a422cb000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0a422b0000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0a420be000)
/lib64/ld-linux-x86-64.so.2 (0x00007f0a42795000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0a41f6f000)

**Comment by mpietras** [comment] 2021-02-19 19:07
I followed instructions here for building grpc: https://grpc.io/docs/languages/cpp/quickstart/
Then I:
git clone https://github.com/googleapis/googleapis.git
cd googleapis
make all

**Comment by coryan** [comment] 2021-02-19 19:39
@mpietras brilliant, reproduced on the first try:

```
[libprotobuf FATAL /source/grpc/third_party/protobuf/src/google/protobuf/io/printer.cc:142]  Unclosed variable name.
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():   Unclosed variable name.
--grpc_out: protoc-gen-grpc: Plugin killed by signal 6.
make: *** [Makefile:45: google/maps/routes/v1/route_service.pb.cc] Error 1
```

I used this script:

[repro-cpp-samples-113-v3.Dockerfile.txt](https://github.com/GoogleCloudPlatform/cpp-samples/files/6012534/repro-cpp-samples-113-v3.Dockerfile.txt)


I am going to open a bug with the gRPC folks, I think there is something wrong with their instructions, or their submodules do not point to the right versions, or something.

**Comment by coryan** [comment] 2021-02-19 20:58
As a workaround, this patches the files to get them to build:

```shell
sed -i 's/\$fields/fields/' google/maps/routes/v1/route_service.proto
sed -i 's/\$fields/fields/' google/maps/routes/v1alpha/route_service.proto
```

That just changes some comments, so it should be safe (cue the ominous music). 

I tested with [repro-cpp-samples-113-v4.Dockerfile.txt](https://github.com/GoogleCloudPlatform/cpp-samples/files/6012900/repro-cpp-samples-113-v4.Dockerfile.txt)

**Comment by mpietras** [comment] 2021-02-19 21:07
That did indeed get me past that issue - thank you!

**Comment by coryan** [comment] 2022-06-08 13:31
I am going to close this, as it appears to be an issue with gRPC, and there is already a tracking bug with gRPC.

**Closed by coryan** 2022-06-08 13:31 UTC
Labels: priority: p2, external, type: bug
