### ISSUE TITLE
run streaming_transcribe Error in windows 

### ISSUE THREAD

**Issue by lichao252244354** [GoogleCloudPlatform/cpp-samples#187] opened 2022-05-20 03:35 UTC
when  Debug std::streamsize bytes_read = file_stream.rdbuf()->sgetn(&chunk[0], chunk.size()) ；I found return value bytes_read is 0, then program error ： "Sending 0 k bytes." I use Visual studio 2019 environment ，please  help me solve this problem，The audio I use in cpp-samples/api/resource ,thank you very much

**Comment by coryan** [comment] 2022-05-20 13:41
I think the problem is here:

https://github.com/GoogleCloudPlatform/cpp-samples/blob/6afcd1c656a7fe3a3a1e0f9e42bf1ab755c97fbc/speech/api/streaming_transcribe.cc#L41

That should be 

```cc
std::ifstream file_stream(file_path, std::ios::binary);
```

I will send a PR, but since we only tests these on Windows, it would help if you could let us know if that fixed the problem.

**Comment by lichao252244354** [comment] 2022-05-20 14:32
thank you very much , I use the std::ifstream file_stream(file_path, std::ios::binary),  it seem's not work , I thank you can Debug in Vsiual Studio 2019 , could you tell me your email ,I can send you more information

**Comment by coryan** [comment] 2022-05-20 14:50
Okay, let me set up my Windows environment (it may take a couple of hours).  Meanwhile: is your input file size a multiple of 64 * 1024?  I think I can see the bug if that is the case.

**Comment by lichao252244354** [comment] 2022-05-20 15:07
I use test Audio file 1.82MB ,wav file

**Comment by lichao252244354** [comment] 2022-05-20 15:17
you can test the resource/audio.flac in windows environment ,I want to ask if wav format audio can also be supported

**Comment by coryan** [comment] 2022-05-20 15:26
I am no expert on audio formats and/or encodings.  The best I can do is point you to the service documentation, for example:

https://cloud.google.com/speech-to-text/docs/encoding

Looks to me that WAV files are supported.

**Comment by coryan** [comment] 2022-05-20 20:09
I just sent a PR (#189) to get this code to compile on Windows.  I was able to run the `streaming_transcribe` program using `resource/audio.flac` successfully.  Let us know if you you are still experiencing problems after that PR is merged.

**Closed** 2022-05-20 21:10 UTC

**Comment by lichao252244354** [comment] 2022-05-21 09:53
Thank you very much, I can use it again here，This issue can be closed
